name: Build & Publish Docker Image

on:
  push:
    tags:
      - 'ComfyUI-*'
      - 'ComfyScale-*'

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Extract branch
        id: branch
        run: |
          TAG=${{ steps.tag.outputs.tag }}
          BRANCH_NAME="${TAG%%-*}"
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO }}/${{ steps.branch.outputs.branch }}:${{ steps.tag.outputs.tag }}
